version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mern
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:5000"
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"

